### ISSUE TITLE
Bitwise read/write

### ISSUE THREAD

**Issue by ceremcem** [ptrks/node-omron-fins#13]
As of now, there is no bitwise (bit by bit) read/write functions available. 

Reading a bit is not so important because we can read a word and use desired bit inside the word, that might be handled in the application. 

But writing a `bit` is a more complex operation (like database transactions) so it should be included/exposed by the library, possibly with a "dot notation" format: 

```ls
client.write "C100.01", true/false
```

**Comment by CharlieMarshall** [comment]
I would like to implement this, although time is against me. When I looked at the Omron manual, it seemed that MEMORY AREA WRITE can only write a WORD to the PLC. Therefore I think we would have to read a WORD to get its current value, amend the BIT value we wanted to write and then send that WORD back to the PLC.

Can anyone see a better way of doing this?

**Comment by ceremcem** [comment]
Mentioned PR's satisfies this issue. Thank you.
